format = """
[░▒▓](#a3aed2)\
[ \uf303 ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$c\
$zig\
$lua\
$rust\
[](fg:#212736 bg:#1d2230)\
$time\
[ ](fg:#1d2230)\
\n$character"""
add_newline = true
scan_timeout = 1000

[character]
success_symbol = '[➜](bold blue)'
error_symbol = '[x](bold red)'

[directory]
fish_style_pwd_dir_length = 1
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncate_to_repo = false

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[c]
symbol = ""
style = "bg:#212736"                                                                              
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[lua]
symbol = ""
style = "bg:#212736"                                                                    
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[zig]
symbol = ""
style = "bg:#212736"                                                                             
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)' 

[time]
disabled = false
time_format = "%R"
style = "bg:#1d2235"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'
